### PR TITLE
Pa 72 pomodoro backend

### PR DESCRIPTION
**Pull request by usefSaeed**
Progress:
- JPA Repo fully implemented and tested
- Controller fully implemented
- Service fully implemented

Tasks to be done post merge in **#PA-85 Pomodoro Backend Unit Testing**:
- Service Tests
- Contoller Tests

After testing is done, I can make another pull request on feature branch to link with the currently in progress tasks: **#PA-74 Pomodoro Integration** and **#PA-71 Pomodoro UI Design and  Frontend**

### CODE REVIEW

**Review by NoirFLamme — CHANGES_REQUESTED** [review]
Remove the commented part in the security configuration class.

**Review by Basel-byte — APPROVED** [review]
- Great work, I will start integrating pomodoro front-end with backend.

**Comment by usefSaeed** [comment]
> Remove the commented part in the security configuration class.

Done

**Review by NoirFLamme — APPROVED** [review]
Great job!

**Pull request merged**
