### PR TITLE
PA-79 fixed backend bug

### PR DESCRIPTION
**Pull request by Ghost8345**
A rogue @Autowired was randomly above the function getTask()

### CODE REVIEW

**Review by AliELSharawy — APPROVED** [review]
DB password error again :(

**Comment by Ghost8345** [comment]
> DB password error again :(

nope an even worse error 🥲

**Comment by AliELSharawy** [comment]
but here you removed @Autowired and changed DB password

**Comment by AliELSharawy** [comment]
> > DB password error again :(
> 
> nope an even worse error 🥲

but here you just deleted @Autowired annotation and changed DB password

**Comment by Ghost8345** [comment]
> > > DB password error again :(
> > 
> > 
> > nope an even worse error 🥲
> 
> but here you just deleted @Autowired annotation and changed DB password

Yes what I mean was what caused the error was the @Autowired annotation not the DB password.

**Review by NoirFLamme — APPROVED** [review]

**Pull request merged**
