### PR TITLE
PA-10-design UI for login register

### PR DESCRIPTION
**Pull request by Ghost8345**
Created the assets and design of both web and mobile app versions, including the sign-up and login page.

### CODE REVIEW

**Review by ZyadSamy — COMMENTED** [review]
Shouldn't the signup form include his name?

**Comment by Ghost8345** [comment]
Not necessarily he can change and set his name in the user profile section after signing up and logging in but it's a design decision. I think it wouldn't make a big difference, but I'm willing to change it if it improves usability.

**Comment by Ghost8345** [comment]
I agree it would be better for usability. I'll change it ASAP.

**Comment by Ghost8345** [comment]
Done. I added a new commit and pushed it to my branch but idk how to integrate it into this pull request, or is it already integrated automatically.

**Comment by ZyadSamy** [comment]
As long as the commit is on the same branch you did the pull request on, it will be updated automatically.

**Review by ZyadSamy — APPROVED** [review]

**Review by Basel-byte — APPROVED** [review]
Well done bro.

**Pull request merged**
