### PR TITLE
Pa 49 design sticky notes UI

### PR DESCRIPTION
**Pull request by Ghost8345**
Implemented Web and Mobile designs for the Notes feature. Please check the .fig file and run the prototype as it has some interactions. Also, I abstracted some interactions as it seemed intuitive but if you feel like you don't understand why a particular icon or button is there please tell me and I'll do my best to explain.

### CODE REVIEW

**Review by usefSaeed — COMMENTED** [review]
Great work.
I have two inquiries though:
1. What will happpen when clicking the three dots on the top right of note component?
2. Can the user favourite more than one note?
    2 .1. If not ... how will this be UI-ly handled by the notes component design

**Comment by Ghost8345** [comment]
> Great work. I have two inquiries though:
> 
>     1. What will happpen when clicking the three dots on the top right of note component?
> 
>     2. Can the user favourite more than one note?
>        2 .1. If not ... how will this be UI-ly handled by the notes component design

1-> 
image
if you mean this icon then this will show a drop-down menu of options for a note; Like moving note to a different folder or other options that we can think of in the future.

2-> Yes he can, how we will show this is a design decision. We can have either a starred folder there by default that can't be deleted or we can show starred notes in Home Component.

**Comment by usefSaeed** [comment]
> Okay, Great.
Just one more request:
Add the options to the dropdown menu in figma when button is clicked so that the UI and backend devloper have a concrete prototype to work with.
Make sure to recheck the the class diagram of the Note component, then add the dropdown options accordingly. Add more options according to your view of the user story if you want.

**Review by usefSaeed — APPROVED** [review]
Yes. That's quite optimal :)

**Pull request merged**
