### PR TITLE
PA-69 Move Note Fully Integrated

### PR DESCRIPTION
**Pull request by Ghost8345**
Integrated the Functionality of Move Note with Backend and Front End fully with both Web and Mobile versions

### CODE REVIEW

**Comment by AliELSharawy** [comment]
Great ♥️
Is database and tests work as expected?

**Comment by Ghost8345** [comment]
> 

Yes.

**Comment by Ghost8345** [comment]
@AliELSharawy the problem was getRefrenceById when sending it to front it doesn't work.

**Comment by AliELSharawy** [comment]
I think get reference by ID should be used to modify object reference in DB so I will check it in note manager if it needs to be modified

**Review by AliELSharawy — APPROVED** [review]

**Comment by NoirFLamme** [comment]
The milestone version you worked on is outdated and your edits aren't working with the new one as some dependencies aren't included.
Please calibrate your work with updated branch.

**Pull request closed without merging**
