### PR TITLE
Pa 73 unify app theme

### PR DESCRIPTION
**Pull request by Ghost8345**
Unified app theme, Fixed Name issue in Home Page, Integrated Starred Notes with Backend

### CODE REVIEW

**Comment by NoirFLamme** [comment]
Great job!
I verified that everything works correctly but there is one minor change that I want you to do:
In `theme.js`:
You are using the font "Montserrat" and you have it imported in the fonts but it isn't referenced in the file.
Please add its reference and make sure it works on your PC by:
- Uninstalling the font from your PC.
- Testing it out after importing it from the fonts folder.

**Comment by Ghost8345** [comment]
> Great job! I verified that everything works correctly but there is one minor change that I want you to do: In `theme.js`: You are using the font "Montserrat" and you have it imported in the fonts but it isn't referenced in the file. Please add its reference and make sure it works on your PC by:
> 
>     * Uninstalling the font from your PC.
> 
>     * Testing it out after importing it from the fonts folder.

Done.

**Comment by NoirFLamme** [comment]
> 

Great job and keep up the good work!

**Review by NoirFLamme — APPROVED** [review]

**Review by AliELSharawy — APPROVED** [review]
gamed 3ash yasta

**Pull request merged**
