### PR TITLE
Pomodoro frontend API

### PR DESCRIPTION
**Pull request by AliELSharawy**
this API is designed with backend controller and frontend just need calling API functions @Basel-byte

### CODE REVIEW

**Comment by NoirFLamme** [comment]
Did you align your frontend API with the aforementioned back-end edits that @usefSaeed mentioned?

**Comment by AliELSharawy** [comment]
> Did you align your frontend API with the aforementioned back-end edits that @usefSaeed was talking about?

yes, last updated with @usefSaeed

**Review by usefSaeed — CHANGES_REQUESTED** [review]
Very good. All changes match what we last agreed upon.
Though, @Basel-byte and I decided to add 2 more APIs to controller
1. reset
2. endStudy

There is the new null controller for simplicity
image

Add these two functions and fir now, we're good to go :)

**Comment by AliELSharawy** [comment]
> Please wait for the pull request of task #PA-72-Pomodoro-Backend as there has been recent updates.

new API functions included in this version.
please check them @usefSaeed

**Comment by AliELSharawy** [comment]
I will resolve some annotations conflicts

**Review by usefSaeed — CHANGES_REQUESTED** [review]
Very good. 
Now, please merge your branch with branch **#PA-71 Pomodoro UI Design and Frontend** as @Basel-byte is still working on it and both your issues are related.
That so you can both continue integration together and then make a pull request on feature branch.

**Comment by AliELSharawy** [comment]
> Very good. Now, please merge your branch with branch **#PA-71 Pomodoro UI Design and Frontend** as @Basel-byte is still working on it and both your issues are related. That so you can both continue integration together and then make a pull request on feature branch.

Done

**Review by Basel-byte — APPROVED** [review]
Great job.

**Pull request merged**
